services:
  redis:
    image: redis:7.4-alpine@sha256:858f009f9709ce576febc734aa78b8f6d624b82571f9ddb6bda4377c833b3499
    ports:
      - '127.0.0.1:6380:6379'
    command:
      [
        'redis-server',
        '--save',
        '',
        '--appendonly',
        'no',
        '--maxmemory',
        '64mb',
        '--maxmemory-policy',
        'noeviction',
      ]
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 1s
      retries: 10
